
const data =[
    {
        EMP_ID: "E0001",
       FirstName: "Meher Krishna",
        LastName: "Vaddadi",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Sep-19",
        Designation: "Managing Director",
        DOB: "17-Oct-80",
       Email_ID: "mvaddadi@red-shift.us"
    },
    {
        EMP_ID: "E0003",
       FirstName: "Sameer",
        LastName: "Shaik Zunaid",
        Gender: "Male",
        Status: "Active",
        DOJ: "16-Apr-19",
        Designation: "Senior Software Analyst",
        DOB: "03-Nov-96",
       Email_ID: "ssameer@red-shift.us"
    },
    {
        EMP_ID: "E0004",
       FirstName: "Soorya Kumar",
        LastName: "Ilango",
        Gender: "Male",
        Status: "Active",
        DOJ: "16-Apr-19",
        Designation: "Senior Software Analyst",
        DOB: "10-Nov-95",
       Email_ID: "silango@red-shift.us"
    },
    {
        EMP_ID: "E0006",
       FirstName: "Phanendra",
        LastName: "Podeti",
        Gender: "Male",
        Status: "Active",
        DOJ: "19-Sep-20",
        Designation: "HR Admin",
        DOB: "11-Oct-92",
       Email_ID: "phanendra.podeti@red-shift.us"
    },
    {
        EMP_ID: "E0010",
       FirstName: "Pravalika",
        LastName: "Gannavaram",
        Gender: "Female",
        Status: "Active",
        DOJ: "01-Dec-20",
        Designation: "Software Analyst",
        DOB: "12-Mar-97",
       Email_ID: "pgannavaram@red-shift.us"
    },
    {
        EMP_ID: "E0011",
       FirstName: "Muralidhar",
        LastName: "Kottanna",
        Gender: "Male",
        Status: "Active",
        DOJ: "15-Feb-21",
        Designation: "\"Director, Program Management\"",
        DOB: "05-Dec-80",
       Email_ID: "mkottana@red-shift.us"
    },
    {
        EMP_ID: "E0013",
       FirstName: "Jyothi",
        LastName: "Sharma",
        Gender: "Female",
        Status: "Active",
        DOJ: "10-May-21",
        Designation: "Project Manager",
        DOB: "24-Dec-95",
       Email_ID: "jsharma@red-shift.us"
    },
    {
        EMP_ID: "E0015",
       FirstName: "Rupali",
        LastName: "Swain",
        Gender: "Female",
        Status: "Active",
        DOJ: "28-Jun-21",
        Designation: "QA Analyst",
        DOB: "24-Nov-96",
       Email_ID: "rswain@red-shift.us"
    },
    {
        EMP_ID: "E0017",
       FirstName: "SASIKALA",
        LastName: "A",
        Gender: "Female",
        Status: "Active",
        DOJ: "19-Jul-21",
        Designation: "QA Analyst",
        DOB: "17-Oct-94",
       Email_ID: "asasikala@red-shift.us"
    },
    {
        EMP_ID: "E0018",
       FirstName: "AJAY",
        LastName: "SINGAMSETTY",
        Gender: "Male",
        Status: "Active",
        DOJ: "19-Jul-21",
        Designation: "Software Analyst",
        DOB: "16-Oct-97",
       Email_ID: "asingamsetty@red-shift.us"
    },
    {
        EMP_ID: "E0019",
       FirstName: "Sravanthi",
        LastName: "Shivannagari",
        Gender: "Female",
        Status: "Active",
        DOJ: "19-Jul-21",
        Designation: "Software Analyst",
        DOB: "10-Apr-99",
       Email_ID: "ssravanthi@red-shift.us"
    },
    {
        EMP_ID: "E0023",
       FirstName: "Madhusudan",
        LastName: "Patra",
        Gender: "Male",
        Status: "Active",
        DOJ: "28-Jul-21",
        Designation: "Senior Technical Manager",
        DOB: "08-Jun-86",
       Email_ID: "mpatra@red-shift.us"
    },
    {
        EMP_ID: "E0025",
       FirstName: "Ravi Kalyan",
        LastName: "Devara",
        Gender: "Male",
        Status: "Active",
        DOJ: "11-Oct-21",
        Designation: "HR Manager",
        DOB: "13-Oct-79",
       Email_ID: "rdevara@red-shift.us"
    },
    {
        EMP_ID: "E0027",
       FirstName: "Sai Teja",
        LastName: "Molabanti",
        Gender: "Male",
        Status: "Active",
        DOJ: "24-Jan-22",
        Designation: "Sr. QA Analyst",
        DOB: "16-Jun-94",
       Email_ID: "smolabanti@red-shift.us"
    },
    {
        EMP_ID: "E0029",
       FirstName: "Prabhu",
        LastName: "PM",
        Gender: "Male",
        Status: "Active",
        DOJ: "14-Feb-22",
        Designation: "QA Analyst",
        DOB: "23-Nov-97",
       Email_ID: "prabhupm@red-shift.us"
    },
    {
        EMP_ID: "E0030",
       FirstName: "Jothsnavi",
        LastName: "Siriki Venkata Satya",
        Gender: "Female",
        Status: "Active",
        DOJ: "14-Feb-22",
        Designation: "QA Analyst",
        DOB: "31-Jul-96",
       Email_ID: "jsiriki@red-shift.us"
    },
    {
        EMP_ID: "E0031",
       FirstName: "Bindu Deepika",
        LastName: "Vallepu",
        Gender: "Female",
        Status: "Active",
        DOJ: "14-Feb-22",
        Designation: "Associate QA Analyst",
        DOB: "24-Aug-96",
       Email_ID: "bvallepu@red-shift.us"
    },
    {
        EMP_ID: "E0032",
       FirstName: "Sravya",
        LastName: "Moturi",
        Gender: "Female",
        Status: "Active",
        DOJ: "03-Mar-22",
        Designation: "Lead Consultant",
        DOB: "24-May-95",
       Email_ID: "smoturi@red-shift.us"
    },
    {
        EMP_ID: "E0033",
       FirstName: "Jahnavi",
        LastName: "Chalasani",
        Gender: "Female",
        Status: "Active",
        DOJ: "11-Apr-22",
        Designation: "Associate QA Analyst",
        DOB: "13-Aug-00",
       Email_ID: "jchalasani@red-shift.us"
    },
    {
        EMP_ID: "E0034",
       FirstName: "Mahesh Babu",
        LastName: "Mullapudi",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Sep-22",
        Designation: "Associate Software Analyst",
        DOB: "21-Jan-97",
       Email_ID: "mmullapudi@red-shift.us"
    },
    {
        EMP_ID: "E0036",
       FirstName: "Pavan Sai",
        LastName: "Birudula",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Sep-22",
        Designation: "Associate Software Analyst",
        DOB: "17-May-97",
       Email_ID: "pbirudula@red-shift.us"
    },
    {
        EMP_ID: "E0037",
       FirstName: "Tejdeep",
        LastName: "S",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Sep-22",
        Designation: "Associate QA Analyst",
        DOB: "10-Mar-97",
       Email_ID: "tsreddy@red-shift.us"
    },
    {
        EMP_ID: "E0038",
       FirstName: "Kalyani",
        LastName: "Chakka S V",
        Gender: "Female",
        Status: "Active",
        DOJ: "13-Jul-22",
        Designation: "Sterling OMS Analyst",
        DOB: "13-May-97",
       Email_ID: "kchakka@red-shift.us"
    },
    {
        EMP_ID: "E0039",
       FirstName: "Satyanarayana",
        LastName: "Dooda Sai Venkata Gopala",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Oct-22",
        Designation: "Associate QA Analyst",
        DOB: "11-Jan-00",
       Email_ID: "sdodda@red-shift.us"
    },
    {
        EMP_ID: "E0040",
       FirstName: "Dinesh",
        LastName: "Pogiri",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Oct-22",
        Designation: "Associate QA Analyst",
        DOB: "18-May-95",
       Email_ID: "dpogiri@red-shift.us"
    },
    {
        EMP_ID: "E0042",
       FirstName: "Moulika",
        LastName: "Kodi",
        Gender: "Female",
        Status: "Active",
        DOJ: "15-Mar-23",
        Designation: "Associate QA Analyst",
        DOB: "21-Jun-02",
       Email_ID: "mkodi@red-shift.us"
    },
    {
        EMP_ID: "E0043",
       FirstName: "Lavanya",
        LastName: "Varada",
        Gender: "Female",
        Status: "Active",
        DOJ: "02-May-23",
        Designation: "Associate QA Analyst",
        DOB: "10-Oct-01",
       Email_ID: "lvarada@red-shift.us"
    },
    {
        EMP_ID: "E0045",
       FirstName: "Sharmila",
        LastName: "Bamidipati",
        Gender: "Female",
        Status: "Active",
        DOJ: "02-May-23",
        Designation: "Associate QA Analyst",
        DOB: "26-Jul-02",
       Email_ID: "sbamidipati@red-shift.us"
    },
    {
        EMP_ID: "E0046",
       FirstName: "Lakshmana",
        LastName: "Chintala",
        Gender: "Male",
        Status: "Active",
        DOJ: "15-Mar-23",
        Designation: "Associate Software Analyst",
        DOB: "04-Jul-02",
       Email_ID: "lchintala@red-shift.us"
    },
    {
        EMP_ID: "E0047",
       FirstName: "Kalyani",
        LastName: "Bommana",
        Gender: "Female",
        Status: "Active",
        DOJ: "22-Mar-23",
        Designation: "Associate QAAnalyst",
        DOB: "28-Jun-02",
       Email_ID: "kbommana@red-shift.us"
    },
    {
        EMP_ID: "E0048",
       FirstName: "Nandan",
        LastName: "Nakirekanti",
        Gender: "Male",
        Status: "Active",
        DOJ: "15-Mar-23",
        Designation: "Associate Software Analyst",
        DOB: "25-Nov-00",
       Email_ID: "nnakirekanti@red-shift.us"
    },
    {
        EMP_ID: "E0049",
       FirstName: "Sai Pavan",
        LastName: "Kandrakota",
        Gender: "Male",
        Status: "Active",
        DOJ: "02-May-23",
        Designation: "Associate Consultant",
        DOB: "29-Oct-97",
       Email_ID: "skandrakota@red-shift.us"
    },
    {
        EMP_ID: "E0051",
       FirstName: "Lakshmi VSSR",
        LastName: "Nemani",
        Gender: "Female",
        Status: "Active",
        DOJ: "07-Dec-22",
        Designation: "Sr. QA Analyst",
        DOB: "03-Jul-80",
       Email_ID: "lnemani@red-shift.us"
    },
    {
        EMP_ID: "E0052",
       FirstName: "Vineela",
        LastName: "Balla",
        Gender: "Female",
        Status: "Active",
        DOJ: "09-Jan-23",
        Designation: "Project Manager",
        DOB: "01-Sep-81",
       Email_ID: "vballa@red-shift.us"
    },
    {
        EMP_ID: "E0053",
       FirstName: "Rajyavardhan",
        LastName: "Abbireddi VSNR",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "03-Jun-01",
       Email_ID: "rabbireddi@red-shift.us"
    },
    {
        EMP_ID: "E0055",
       FirstName: "Sahithi",
        LastName: "Narayana Priyamvadha Nasari",
        Gender: "Female",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "06-May-02",
       Email_ID: "snasari@red-shift.us"
    },
    {
        EMP_ID: "E0056",
       FirstName: "Dhanush",
        LastName: "Doma Venkata",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "03-Oct-01",
       Email_ID: "ddomavenkata@red-shift.us"
    },
    {
        EMP_ID: "E0057",
       FirstName: "Gowrish",
        LastName: "Janupalli",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "29-Dec-00",
       Email_ID: "gjanupalli@red-shift.us"
    },
    {
        EMP_ID: "E0058",
       FirstName: "Mahesh",
        LastName: "Kella",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "13-Oct-01",
       Email_ID: "mkella@red-shift.us"
    },
    {
        EMP_ID: "E0059",
       FirstName: "Charan Teja",
        LastName: "Allipilli",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "04-Oct-01",
       Email_ID: "callipilli@red-shift.us"
    },
    {
        EMP_ID: "E0061",
       FirstName: "Krishna Saketh",
        LastName: "Mannava V N S Manikanta",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "14-Nov-02",
       Email_ID: "kmannava@red-shift.us"
    },
    {
        EMP_ID: "E0062",
       FirstName: "Ajit",
        LastName: "Bade",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "01-Sep-01",
       Email_ID: "abade@red-shift.us"
    },
    {
        EMP_ID: "E0063",
       FirstName: "Sai Chaitanya",
        LastName: "Tutika",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "18-Feb-02",
       Email_ID: "stutika@red-shift.us"
    },
    {
        EMP_ID: "E0064",
       FirstName: "Nitin",
        LastName: "Akode",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "13-Dec-01",
       Email_ID: "nakode@red-shift.us"
    },
    {
        EMP_ID: "E0065",
       FirstName: "Naveen Kumar",
        LastName: "Nampally",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "19-Mar-00",
       Email_ID: "nnampally@red-shift.us"
    },
    {
        EMP_ID: "E0067",
       FirstName: "Noshitha Sai",
        LastName: "Empati",
        Gender: "Female",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "03-Oct-00",
       Email_ID: "nempati@red-shift.us"
    },
    {
        EMP_ID: "E0068",
       FirstName: "Sreepada Vallabh",
        LastName: "Veleti",
        Gender: "Male",
        Status: "Active",
        DOJ: "18-Jan-23",
        Designation: "Associate Software Analyst",
        DOB: "13-Mar-01",
       Email_ID: "sveleti@red-shift.us"
    },
    {
        EMP_ID: "E0069",
        FirstName: "Sri Vamsi",
        LastName: "Chalamalasetti",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Feb-23",
        Designation: "Associate Software Analyst",
        DOB: "23-Aug-99",
       Email_ID: "vchalamalasetti@red-shift.us"
    },
    {
        EMP_ID: "E0070",
       FirstName: "Abilash",
        LastName: "Kurakula",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Feb-23",
        Designation: "Associate Software Analyst",
        DOB: "19-Apr-00",
       Email_ID: "akurakula@red-shift.us"
    },
    {
        EMP_ID: "E0071",
       FirstName: "Manoj Kumar",
        LastName: "Lingampally",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Jun-21",
        Designation: "Associate Software Analyst",
        DOB: "25-Sep-00",
       Email_ID: "mlingampally@red-shift.us"
    },
    {
        EMP_ID: "E0072",
       FirstName: "Mukesh Reddy",
        LastName: "Kancharala",
        Gender: "Male",
        Status: "Active",
        DOJ: "01-Feb-23",
        Designation: "Associate Software Analyst",
        DOB: "24-Jul-01",
       Email_ID: "mkancharla@red-shift.us"
    },
    {
        EMP_ID: "E0073",
       FirstName: "LAKSHMI NELLIMA",
        LastName: "VELUGULA",
        Gender: "Female",
        Status: "Active",
        DOJ: "01-Jun-21",
        Designation: "Technical Manager",
        DOB: "01-Jun-79",
       Email_ID: "lvelugula@red-shift.us"
    },
    {
        EMP_ID: "E0074",
       FirstName: "Sakthivel",
        LastName: "TN",
        Gender: "Male",
        Status: "Active",
        DOJ: "21-Mar-23",
        Designation: "Senior Support Consultant",
        DOB: "18-May-72",
       Email_ID: "tnsakthivel@red-shift.us"
    }
]
export default data