export {default as Sidenavbar} from './sidenavbar/Sidenavbar' 
export {default as Topnavbar} from './topnavbar/Topnavbar' 
export {default as Details} from './details/Details'
export {default as ResponsiveAppBar} from './ex/ResponsiveAppBar'
export {default as Content}    from './content/Content'